# Generated by Django 3.0.6 on 2020-05-19 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afscraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
